# Copyright (c) 2024 - 2025 Kevin G. Schlosser

name: ESP32-P4 build

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build_esp32p4:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - board: ESP32_GENERIC_P4
            flash_size: 8
            variant: null
            name: ESP32_GENERIC_P4-8
          - board: ESP32_GENERIC_P4
            flash_size: 8
            variant: C6_WIFI
            name: ESP32_GENERIC_P4-C6_WIFI-8

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6.1.0
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        git submodule update --init --depth 1 -- lib/pycparser
        git submodule update --init --depth 1 --jobs 4 -- lib/micropython
        git submodule update --init --depth 1 --jobs 4 -- lib/lvgl

    - name: Cached ESP-IDF Dependencies
      id: cache-deps
      uses: actions/cache@v4.3.0
      with:
        path: |
          lib/esp-idf
          ~/.espressif
        key: ${{ runner.os }}-v4-esp-idf-deps

    - name: Get ESP-IDF Build Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        git submodule update --init --depth 1 --jobs 4 -- lib/esp-idf
        cd lib/esp-idf
        git submodule update --init --depth 1 --jobs 4 -- components/bt/host/nimble/nimble components/esp_wifi components/esptool_py/esptool components/lwip/lwip components/mbedtls/mbedtls components/bt/controller/lib_esp32 components/bt/controller/lib_esp32c3_family
        cd ../..
        export "IDF_PATH=${GITHUB_WORKSPACE}/lib/esp-idf"
        ./lib/esp-idf/install.sh all

    - name: Build ${{ matrix.name }}
      run: |
        export "IDF_PATH=${GITHUB_WORKSPACE}/lib/esp-idf"
        . ./lib/esp-idf/export.sh
        if [ -z "${{ matrix.variant }}" ]; then
          python3 make.py esp32 BOARD=${{ matrix.board }} --flash-size=${{ matrix.flash_size }} DISPLAY=all INDEV=all EXPANDER=all --ccache --no-scrub
        else
          python3 make.py esp32 BOARD=${{ matrix.board }} --flash-size=${{ matrix.flash_size }} BOARD_VARIANT=${{ matrix.variant }} DISPLAY=all INDEV=all EXPANDER=all --ccache --no-scrub
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: lvgl_micropy_${{ matrix.name }}
        path: build/*.bin
        if-no-files-found: error
